/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment.success'
import { Route as AuthenticatedBarScannerRouteImport } from './routes/_authenticated/bar.scanner'
import { Route as AuthenticatedAppQrRouteImport } from './routes/_authenticated/app.qr'
import { Route as AuthenticatedAppDrinksRouteImport } from './routes/_authenticated/app.drinks'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBarScannerRoute = AuthenticatedBarScannerRouteImport.update({
  id: '/bar/scanner',
  path: '/bar/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppQrRoute = AuthenticatedAppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDrinksRoute = AuthenticatedAppDrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/drinks': typeof AuthenticatedAppDrinksRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/bar/scanner': typeof AuthenticatedBarScannerRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/drinks': typeof AuthenticatedAppDrinksRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/bar/scanner': typeof AuthenticatedBarScannerRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/drinks': typeof AuthenticatedAppDrinksRoute
  '/_authenticated/app/qr': typeof AuthenticatedAppQrRoute
  '/_authenticated/bar/scanner': typeof AuthenticatedBarScannerRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/drinks'
    | '/app/qr'
    | '/bar/scanner'
    | '/payment/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/drinks'
    | '/app/qr'
    | '/bar/scanner'
    | '/payment/success'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/app'
    | '/_authenticated/app/drinks'
    | '/_authenticated/app/qr'
    | '/_authenticated/bar/scanner'
    | '/_authenticated/payment/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bar/scanner': {
      id: '/_authenticated/bar/scanner'
      path: '/bar/scanner'
      fullPath: '/bar/scanner'
      preLoaderRoute: typeof AuthenticatedBarScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/qr': {
      id: '/_authenticated/app/qr'
      path: '/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AuthenticatedAppQrRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/drinks': {
      id: '/_authenticated/app/drinks'
      path: '/drinks'
      fullPath: '/app/drinks'
      preLoaderRoute: typeof AuthenticatedAppDrinksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDrinksRoute: typeof AuthenticatedAppDrinksRoute
  AuthenticatedAppQrRoute: typeof AuthenticatedAppQrRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDrinksRoute: AuthenticatedAppDrinksRoute,
  AuthenticatedAppQrRoute: AuthenticatedAppQrRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBarScannerRoute: typeof AuthenticatedBarScannerRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBarScannerRoute: AuthenticatedBarScannerRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
