/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment.success'
import { Route as AuthenticatedBarScannerRouteImport } from './routes/_authenticated/bar.scanner'
import { Route as AuthenticatedAppQrRouteImport } from './routes/_authenticated/app.qr'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppDrinksRouteImport } from './routes/_authenticated/app.drinks'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin.volunteers'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminShiftsRouteImport } from './routes/_authenticated/admin.shifts'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBarScannerRoute = AuthenticatedBarScannerRouteImport.update({
  id: '/bar/scanner',
  path: '/bar/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppQrRoute = AuthenticatedAppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDrinksRoute = AuthenticatedAppDrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShiftsRoute =
  AuthenticatedAdminShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/app/drinks': typeof AuthenticatedAppDrinksRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/bar/scanner': typeof AuthenticatedBarScannerRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/app/drinks': typeof AuthenticatedAppDrinksRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/bar/scanner': typeof AuthenticatedBarScannerRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/app/drinks': typeof AuthenticatedAppDrinksRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/qr': typeof AuthenticatedAppQrRoute
  '/_authenticated/bar/scanner': typeof AuthenticatedBarScannerRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/app'
    | '/admin/analytics'
    | '/admin/payments'
    | '/admin/shifts'
    | '/admin/tickets'
    | '/admin/volunteers'
    | '/app/drinks'
    | '/app/history'
    | '/app/qr'
    | '/bar/scanner'
    | '/payment/success'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/payments'
    | '/admin/shifts'
    | '/admin/tickets'
    | '/admin/volunteers'
    | '/app/drinks'
    | '/app/history'
    | '/app/qr'
    | '/bar/scanner'
    | '/payment/success'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/shifts'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/app/drinks'
    | '/_authenticated/app/history'
    | '/_authenticated/app/qr'
    | '/_authenticated/bar/scanner'
    | '/_authenticated/payment/success'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bar/scanner': {
      id: '/_authenticated/bar/scanner'
      path: '/bar/scanner'
      fullPath: '/bar/scanner'
      preLoaderRoute: typeof AuthenticatedBarScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/qr': {
      id: '/_authenticated/app/qr'
      path: '/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AuthenticatedAppQrRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/drinks': {
      id: '/_authenticated/app/drinks'
      path: '/drinks'
      fullPath: '/app/drinks'
      preLoaderRoute: typeof AuthenticatedAppDrinksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shifts': {
      id: '/_authenticated/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AuthenticatedAdminShiftsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminShiftsRoute: typeof AuthenticatedAdminShiftsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminShiftsRoute: AuthenticatedAdminShiftsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDrinksRoute: typeof AuthenticatedAppDrinksRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppQrRoute: typeof AuthenticatedAppQrRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDrinksRoute: AuthenticatedAppDrinksRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppQrRoute: AuthenticatedAppQrRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBarScannerRoute: typeof AuthenticatedBarScannerRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBarScannerRoute: AuthenticatedBarScannerRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
